USE CoffeeSales;
GO

/*
===============================================================================
09. PART-TO-WHOLE ANALYSIS
===============================================================================

Purpose:
    Analyze how individual categories contribute to overall business results.

Business Questions:
    1. What percentage of total sales does each coffee type contribute?
    2. What percentage of total sales does each roast type contribute?
    3. What percentage of total sales does each size category contribute?
    4. What percentage of total sales does each country contribute?
    5. What percentage of total sales comes from loyalty vs non-loyalty customers?
    6. What percentage of total quantity sold belongs to each coffee type?
    7. What percentage of total profit does each product contribute?
    8. What percentage of sales is generated by the top 10 customers?
*/


-- =============================================================================
-- Question 1:
-- What percentage of total sales does each coffee type contribute?
-- =============================================================================

WITH CoffeeTypeSales AS (
    SELECT
        p.coffee_type,
        SUM(o.sales) AS coffee_type_sales
    FROM gold.fact_orders AS o
    LEFT JOIN gold.dim_products AS p
        ON o.product_key = p.product_key
    GROUP BY
        p.coffee_type
),

CoffeeTypeContribution AS (
    SELECT
        coffee_type,
        coffee_type_sales,
        SUM(coffee_type_sales) OVER () AS total_sales
    FROM CoffeeTypeSales
)

SELECT
    coffee_type,
    coffee_type_sales,
    total_sales,

    ROUND(
        100.0 * coffee_type_sales
        / NULLIF(total_sales, 0),
        2
    ) AS sales_contribution_percentage

FROM CoffeeTypeContribution
ORDER BY
    sales_contribution_percentage DESC;


-- =============================================================================
-- Question 2:
-- What percentage of total sales does each roast type contribute?
-- =============================================================================

WITH RoastTypeSales AS (
    SELECT
        p.roast_type,
        SUM(o.sales) AS roast_type_sales
    FROM gold.fact_orders AS o
    LEFT JOIN gold.dim_products AS p
        ON o.product_key = p.product_key
    GROUP BY
        p.roast_type
),

RoastTypeContribution AS (
    SELECT
        roast_type,
        roast_type_sales,
        SUM(roast_type_sales) OVER () AS total_sales
    FROM RoastTypeSales
)

SELECT
    roast_type,
    roast_type_sales,
    total_sales,

    ROUND(
        100.0 * roast_type_sales
        / NULLIF(total_sales, 0),
        2
    ) AS sales_contribution_percentage

FROM RoastTypeContribution
ORDER BY
    sales_contribution_percentage DESC;


-- =============================================================================
-- Question 3:
-- What percentage of total sales does each size category contribute?
-- =============================================================================

WITH SizeCategorySales AS (
    SELECT
        p.size_category,
        SUM(o.sales) AS size_category_sales
    FROM gold.fact_orders AS o
    LEFT JOIN gold.dim_products AS p
        ON o.product_key = p.product_key
    GROUP BY
        p.size_category
),

SizeCategoryContribution AS (
    SELECT
        size_category,
        size_category_sales,
        SUM(size_category_sales) OVER () AS total_sales
    FROM SizeCategorySales
)

SELECT
    size_category,
    size_category_sales,
    total_sales,

    ROUND(
        100.0 * size_category_sales
        / NULLIF(total_sales, 0),
        2
    ) AS sales_contribution_percentage

FROM SizeCategoryContribution
ORDER BY
    sales_contribution_percentage DESC;


-- =============================================================================
-- Question 4:
-- What percentage of total sales does each country contribute?
-- =============================================================================

WITH CountrySales AS (
    SELECT
        c.country,
        SUM(o.sales) AS country_sales
    FROM gold.fact_orders AS o
    LEFT JOIN gold.dim_customers AS c
        ON o.customer_key = c.customer_key
    GROUP BY
        c.country
),

CountryContribution AS (
    SELECT
        country,
        country_sales,
        SUM(country_sales) OVER () AS total_sales
    FROM CountrySales
)

SELECT
    country,
    country_sales,
    total_sales,

    ROUND(
        100.0 * country_sales
        / NULLIF(total_sales, 0),
        2
    ) AS sales_contribution_percentage

FROM CountryContribution
ORDER BY
    sales_contribution_percentage DESC;


-- =============================================================================
-- Question 5:
-- What percentage of total sales comes from loyalty vs non-loyalty customers?
-- =============================================================================

WITH LoyaltySales AS (
    SELECT
        c.loyalty_card,
        SUM(o.sales) AS loyalty_group_sales
    FROM gold.fact_orders AS o
    LEFT JOIN gold.dim_customers AS c
        ON o.customer_key = c.customer_key
    GROUP BY
        c.loyalty_card
),

LoyaltyContribution AS (
    SELECT
        loyalty_card,
        loyalty_group_sales,
        SUM(loyalty_group_sales) OVER () AS total_sales
    FROM LoyaltySales
)

SELECT
    loyalty_card,
    loyalty_group_sales,
    total_sales,

    ROUND(
        100.0 * loyalty_group_sales
        / NULLIF(total_sales, 0),
        2
    ) AS sales_contribution_percentage

FROM LoyaltyContribution
ORDER BY
    sales_contribution_percentage DESC;


-- =============================================================================
-- Question 6:
-- What percentage of total quantity sold belongs to each coffee type?
-- =============================================================================

WITH CoffeeTypeQuantity AS (
    SELECT
        p.coffee_type,
        SUM(o.quantity) AS coffee_type_quantity
    FROM gold.fact_orders AS o
    LEFT JOIN gold.dim_products AS p
        ON o.product_key = p.product_key
    GROUP BY
        p.coffee_type
),

QuantityContribution AS (
    SELECT
        coffee_type,
        coffee_type_quantity,
        SUM(coffee_type_quantity) OVER () AS total_quantity
    FROM CoffeeTypeQuantity
)

SELECT
    coffee_type,
    coffee_type_quantity,
    total_quantity,

    ROUND(
        100.0 * coffee_type_quantity
        / NULLIF(total_quantity, 0),
        2
    ) AS quantity_contribution_percentage

FROM QuantityContribution
ORDER BY
    quantity_contribution_percentage DESC;

-- =============================================================================
-- Question 7:
-- What percentage of total profit does each product contribute?
-- =============================================================================

WITH ProductProfit AS (
    SELECT
        p.product_id,
        SUM(o.quantity * p.profit) AS product_profit

    FROM gold.fact_orders AS o

    LEFT JOIN gold.dim_products AS p
        ON o.product_key = p.product_key

    GROUP BY
        p.product_id
),

TotalProductProfit AS (
    SELECT
        product_id,
        product_profit,

        SUM(product_profit) OVER () AS total_profit

    FROM ProductProfit
)

SELECT
    product_id,
    product_profit,
    total_profit,

    ROUND(
        100.0 * product_profit
        / NULLIF(total_profit, 0),
        2
    ) AS profit_contribution_percentage

FROM TotalProductProfit
ORDER BY
    profit_contribution_percentage DESC;

-- =============================================================================
-- Question 8:
-- What percentage of total sales is generated by the top 10 customers?
-- =============================================================================

WITH CustomerSales AS (
    SELECT
        c.customer_id,
        c.customer_name,
        SUM(o.sales) AS customer_sales

    FROM gold.fact_orders AS o

    LEFT JOIN gold.dim_customers AS c
        ON o.customer_key = c.customer_key

    GROUP BY
        c.customer_id,
        c.customer_name
),

RankedCustomers AS (
    SELECT
        customer_id,
        customer_name,
        customer_sales,

        ROW_NUMBER() OVER (
            ORDER BY customer_sales DESC
        ) AS customer_rank

    FROM CustomerSales
),

SalesTotals AS (
    SELECT
        SUM(
            CASE
                WHEN customer_rank <= 10 THEN customer_sales
                ELSE 0
            END
        ) AS top_10_customer_sales,

        SUM(customer_sales) AS total_sales

    FROM RankedCustomers
)

SELECT
    top_10_customer_sales,
    total_sales,

    ROUND(
        100.0 * top_10_customer_sales
        / NULLIF(total_sales, 0),
        2
    ) AS top_10_sales_contribution_percentage

FROM SalesTotals;
